version: "3.8"
services:
  subscriber:
    environment:
      - SERVER_PORT=80
      - MQTT_BROKER_HOST=broker
      - MQTT_BROKER_PORT=1883
      - MQTT_AUTORECONNECT=true
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=y34ujAdNtU3JK6a56wC6
      - DB_NAME=carmon
      - DB_DRIVER=postgres
      - SUBSCRIBER_QOS=1
      - APP_WORKERS_NUMBER=1
    build:
      context: .
      dockerfile: ./builds/Dockerfile
    depends_on:
      - db
      - broker
  db:
    image: "postgres:alpine"
    restart: always
    expose:
      - "5432"
    environment:
      - "POSTGRES_PASSWORD=y34ujAdNtU3JK6a56wC6"
      - "POSTGRES_DB=carmon"
  broker:
    image: "emqx/emqx:4.2.11-alpine-amd64"
    restart: always
    expose:
      - "1883"
    ports:
      - "17083:1883"
  grafana:
    image: "grafana/grafana"
    restart: always
    ports:
      - "23000:3000"
    depends_on:
      - db
