// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: mqtt.proto

package ports

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool                   `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	At     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=At,proto3" json:"At,omitempty"`
}

func (x *StatusNotification) Reset() {
	*x = StatusNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqtt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotification) ProtoMessage() {}

func (x *StatusNotification) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotification.ProtoReflect.Descriptor instead.
func (*StatusNotification) Descriptor() ([]byte, []int) {
	return file_mqtt_proto_rawDescGZIP(), []int{0}
}

func (x *StatusNotification) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *StatusNotification) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type PIDNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventID     string                 `protobuf:"bytes,1,opt,name=EventID,proto3" json:"EventID,omitempty"`
	Value       string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Unit        string                 `protobuf:"bytes,3,opt,name=Unit,proto3" json:"Unit,omitempty"`
	Description string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	At          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=At,proto3" json:"At,omitempty"`
}

func (x *PIDNotification) Reset() {
	*x = PIDNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqtt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PIDNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PIDNotification) ProtoMessage() {}

func (x *PIDNotification) ProtoReflect() protoreflect.Message {
	mi := &file_mqtt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PIDNotification.ProtoReflect.Descriptor instead.
func (*PIDNotification) Descriptor() ([]byte, []int) {
	return file_mqtt_proto_rawDescGZIP(), []int{1}
}

func (x *PIDNotification) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *PIDNotification) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PIDNotification) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *PIDNotification) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PIDNotification) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

var File_mqtt_proto protoreflect.FileDescriptor

var file_mqtt_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x71, 0x74, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x71,
	0x74, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x2a, 0x0a, 0x02, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x41, 0x74, 0x22, 0xa3, 0x01,
	0x0a, 0x0f, 0x50, 0x49, 0x44, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x02, 0x41, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x02, 0x41, 0x74, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x63, 0x65, 0x73, 0x61, 0x72, 0x46, 0x75, 0x68, 0x72, 0x2f, 0x6d, 0x71, 0x74, 0x74,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mqtt_proto_rawDescOnce sync.Once
	file_mqtt_proto_rawDescData = file_mqtt_proto_rawDesc
)

func file_mqtt_proto_rawDescGZIP() []byte {
	file_mqtt_proto_rawDescOnce.Do(func() {
		file_mqtt_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqtt_proto_rawDescData)
	})
	return file_mqtt_proto_rawDescData
}

var file_mqtt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mqtt_proto_goTypes = []interface{}{
	(*StatusNotification)(nil),    // 0: mqtt.StatusNotification
	(*PIDNotification)(nil),       // 1: mqtt.PIDNotification
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_mqtt_proto_depIdxs = []int32{
	2, // 0: mqtt.StatusNotification.At:type_name -> google.protobuf.Timestamp
	2, // 1: mqtt.PIDNotification.At:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mqtt_proto_init() }
func file_mqtt_proto_init() {
	if File_mqtt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqtt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqtt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PIDNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqtt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mqtt_proto_goTypes,
		DependencyIndexes: file_mqtt_proto_depIdxs,
		MessageInfos:      file_mqtt_proto_msgTypes,
	}.Build()
	File_mqtt_proto = out.File
	file_mqtt_proto_rawDesc = nil
	file_mqtt_proto_goTypes = nil
	file_mqtt_proto_depIdxs = nil
}
